<?php include 'header.phtml'; ?>

<?php if (isset($_SESSION['IS_LOGGED'])): ?>
    <?php include 'form_alta.phtml'; ?>
<?php endif; ?>

<!-- lista de categorías -->
<ul class="list-group">
    <?php foreach ($categories as $category): ?>
        <li class="list-group-item d-flex justify-content-between align-items-center">
                <span>
                    <b><a href="category/<?= $category->id ?>"><?= htmlspecialchars($category->nombre) ?></a></b> - 
                    <?= htmlspecialchars(substr($category->descripcion, 0, 50)) ?>
                </span>

            <?php if (isset($_SESSION['IS_LOGGED'])): ?>
                <div class="ml-auto">
                    <a href="editCategory/<?= $category->id ?>" class="btn btn-primary btn-sm">Editar</a>
                    <a href="delete/<?= $category->id ?>" class="btn btn-danger btn-sm">Eliminar</a>
                </div>
            <?php endif; ?>
            
        </li>
    <?php endforeach; ?>
</ul>

<p class="mt-3"><small>Mostrando <?= $count ?> categorías</small></p>

<?php include 'footer.phtml'; ?>
