<?php include 'header.phtml'; ?>

<h2 class="mb-3">Editar Categoría</h2>

<form action="updateCategory/<?= $category->id ?>" method="POST" enctype="multipart/form-data" class="mb-4">
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre:</label>
        <input 
            type="text" 
            id="nombre" 
            name="nombre" 
            value="<?= htmlspecialchars($category->nombre) ?>" 
            class="form-control" 
            required
        >
    </div>

    <div class="mb-3">
        <label for="descripcion" class="form-label">Descripción:</label>
        <textarea 
            id="descripcion" 
            name="descripcion" 
            class="form-control" 
            required
        ><?= htmlspecialchars($category->descripcion) ?></textarea>
    </div>

    <div class="mb-3">
        <label for="imagen" class="form-label">Imagen:</label>
        <input type="file" name="imagen" accept=".jpg,.jpeg,.png" class="form-control">
        <?php if (!empty($category->imagen)): ?>
            <img src="<?= $category->imagen ?>" class="img-fluid mt-2" alt="Imagen de la categoría">
        <?php endif; ?>
    </div>

    <button type="submit" class="btn btn-primary">Guardar cambios</button>
    <a href="<?= BASE_URL ?>" class="btn btn-secondary">Cancelar</a>
</form>


<?php include 'footer.phtml'; ?>
