<!-- formulario de alta de categoría -->
<form action="add" method="POST" class="my-4">
    <div class="form-group">
        <label for="nombre">Nombre de la categoría</label>
        <input name="nombre" id="nombre" type="text" class="form-control" required>
    </div>

    <div class="form-group">
        <label for="descripcion">Descripción</label>
        <textarea name="descripcion" id="descripcion" class="form-control" rows="3" required></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>

</main>
<!-- fin main container -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>
